/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTPVLOGSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTPVLOGSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractPvlogServer : public jsonrpc::AbstractServer<AbstractPvlogServer>
{
    public:
        AbstractPvlogServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractPvlogServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("getSpotData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "date",jsonrpc::JSON_STRING, NULL), &AbstractPvlogServer::getSpotDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getLiveSpotData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getLiveSpotDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getMonthData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "month",jsonrpc::JSON_STRING, NULL), &AbstractPvlogServer::getMonthDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getYearData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "year",jsonrpc::JSON_STRING, NULL), &AbstractPvlogServer::getYearDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getInverter", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getInverterI);
            this->bindAndAddMethod(jsonrpc::Procedure("getPlants", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getPlantsI);
        }

        inline virtual void getSpotDataI(const Json::Value &request, Json::Value &response)
        {
            response = this->getSpotData(request["date"].asString());
        }
        inline virtual void getLiveSpotDataI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getLiveSpotData();
        }
        inline virtual void getMonthDataI(const Json::Value &request, Json::Value &response)
        {
            response = this->getMonthData(request["month"].asString());
        }
        inline virtual void getYearDataI(const Json::Value &request, Json::Value &response)
        {
            response = this->getYearData(request["year"].asString());
        }
        inline virtual void getInverterI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getInverter();
        }
        inline virtual void getPlantsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getPlants();
        }
        virtual Json::Value getSpotData(const std::string& date) = 0;
        virtual Json::Value getLiveSpotData() = 0;
        virtual Json::Value getMonthData(const std::string& month) = 0;
        virtual Json::Value getYearData(const std::string& year) = 0;
        virtual Json::Value getInverter() = 0;
        virtual Json::Value getPlants() = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTPVLOGSERVER_H_
