/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTPVLOGSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTPVLOGSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractPvlogServer : public jsonrpc::AbstractServer<AbstractPvlogServer>
{
    public:
        AbstractPvlogServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractPvlogServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("getSpotData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "date",jsonrpc::JSON_STRING, NULL), &AbstractPvlogServer::getSpotDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getLiveSpotData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getLiveSpotDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getDataloggerStatus", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getDataloggerStatusI);
            this->bindAndAddMethod(jsonrpc::Procedure("getDayData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "from",jsonrpc::JSON_STRING,"to",jsonrpc::JSON_STRING, NULL), &AbstractPvlogServer::getDayDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getMonthData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "year",jsonrpc::JSON_STRING, NULL), &AbstractPvlogServer::getMonthDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getStatistics", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getStatisticsI);
            this->bindAndAddMethod(jsonrpc::Procedure("getYearData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getYearDataI);
            this->bindAndAddMethod(jsonrpc::Procedure("getInverters", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getInvertersI);
            this->bindAndAddMethod(jsonrpc::Procedure("getPlants", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getPlantsI);
            this->bindAndAddMethod(jsonrpc::Procedure("getEvents", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractPvlogServer::getEventsI);
        }

        inline virtual void getSpotDataI(const Json::Value &request, Json::Value &response)
        {
            response = this->getSpotData(request["date"].asString());
        }
        inline virtual void getLiveSpotDataI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getLiveSpotData();
        }
        inline virtual void getDataloggerStatusI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getDataloggerStatus();
        }
        inline virtual void getDayDataI(const Json::Value &request, Json::Value &response)
        {
            response = this->getDayData(request["from"].asString(), request["to"].asString());
        }
        inline virtual void getMonthDataI(const Json::Value &request, Json::Value &response)
        {
            response = this->getMonthData(request["year"].asString());
        }
        inline virtual void getStatisticsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getStatistics();
        }
        inline virtual void getYearDataI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getYearData();
        }
        inline virtual void getInvertersI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getInverters();
        }
        inline virtual void getPlantsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getPlants();
        }
        inline virtual void getEventsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getEvents();
        }
        virtual Json::Value getSpotData(const std::string& date) = 0;
        virtual Json::Value getLiveSpotData() = 0;
        virtual Json::Value getDataloggerStatus() = 0;
        virtual Json::Value getDayData(const std::string& from, const std::string& to) = 0;
        virtual Json::Value getMonthData(const std::string& year) = 0;
        virtual Json::Value getStatistics() = 0;
        virtual Json::Value getYearData() = 0;
        virtual Json::Value getInverters() = 0;
        virtual Json::Value getPlants() = 0;
        virtual Json::Value getEvents() = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTPVLOGSERVER_H_
